apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-2-base

namespace: namespace-app-2-base

resources:
- namespace.yaml
- https://github.com/stakater/Reloader/deployments/kubernetes

patches:
# use patch to remove namespace from non-namespaced objects, which would throw error
- target:
    kind: "Cluster.*|ServiceAccount.*"
  patch: |-
    - op: remove
      path: /metadata/namespace
