apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: namespace-app-1-base

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: nginx-cm
  namespace: namespace-1
  files:
  - cm-index.html

generatorOptions:
  disableNameSuffixHash: true